"""Archetype providers.

Two implementations are shipped:

  - TEASERArchetypeProvider: reads an archetype-input CSV (year, floors,
    area, height) and runs TEASER over a TABULA construction database
    (default: German single-family). Produces a parquet that carries
    parameters for all three thermal-network models (1R1C aggregate,
    ISO 13790 5R1C, and VDI 6007 7R2C) from the same archetype input,
    using the canonical ArchetypeSchema column names.

  - FileArchetypeProvider: reads a user-supplied table (CSV or parquet,
    auto-detected by suffix) that already conforms to ArchetypeSchema.
    Useful when the user has archetypes from a different country or
    generated by another tool (EnergyPlus, EUReCA, hand-curated
    literature values).

Both providers emit the same canonical schema. Files written by an
older version of this codebase that used legacy names like
``area[m2]`` / ``resistance[K W-1]`` must be regenerated — the providers
do NOT auto-translate.

`CSVArchetypeProvider` is kept as a legacy alias of `FileArchetypeProvider`.

References for the higher-fidelity column definitions:
  - ISO 13790:2008, Annex C, for the 5R1C reduction (h_is, h_ms, lambda_at,
    A_m and C_m default values used below).
  - VDI 6007 Part 1, and the AixLib BES Building model, for the
    7R2C topology and the R_alpha_star / R_rest decomposition.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pandas as pd

from .base import ArchetypeSchema, validate_schema


def _load_archetypes_csv(archetypes_path: Path) -> pd.DataFrame:
    """Read the archetype-input CSV and return a TEASER-ready DataFrame.

    Input CSV columns (canonical schema, user-authored):
        archetype_id, construction_year, area_m2, n_floors, height_floor_m

    Output DataFrame columns (TEASER API names — consumed by
    ``TEASERArchetypeProvider._build_one()``):
        archetype_id, year_of_construction, net_leased_area,
        number_of_floors, height_of_floors
    """
    df = pd.read_csv(archetypes_path, comment="#")
    required = {"archetype_id", "construction_year", "area_m2", "n_floors", "height_floor_m"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"{archetypes_path} is missing columns: {sorted(missing)}")
    return df.rename(columns={
        "construction_year": "year_of_construction",
        "area_m2": "net_leased_area",
        "n_floors": "number_of_floors",
        "height_floor_m": "height_of_floors",
    })


# ── ISO 13790 5R1C standard constants (Annex C, residential) ────────────────
# h_is, h_ms: fixed coefficients in the 5R1C reduction
_ISO13790_H_IS = 3.45        # W/(m^2 K), air-to-surface heat transfer coefficient
_ISO13790_H_MS = 9.1         # W/(m^2 K), surface-to-mass heat transfer coefficient
# lambda_at: ratio of total enclosed surface area to floor area (residential default)
_ISO13790_LAMBDA_AT = 4.5
# Building class (medium-medium, ISO 13790 default for residential):
#   A_m / A_floor = 2.5, kappa_m = 165 kJ/(m^2 K) = 165e3 J/(m^2 K)
_ISO13790_A_M_PER_A_FLOOR = 2.5
_ISO13790_KAPPA_M = 165e3    # J/(m^2 K)


def _compose_5r1c(m1, a_floor: float) -> dict:
    """ISO 13790 5R1C parameters from a TEASER one-element model.

    Composition follows ISO 13790:2008 Annex C with the medium-medium
    residential building class. The envelope opaque conductance H_tr_op is
    taken from TEASER's outer-wall UA-value; H_tr_em is then derived from
    the standard series relation 1/H_tr_op = 1/H_tr_em + 1/H_tr_ms.
    """
    # Surface-side coefficients (geometry only, building-class independent)
    a_t = _ISO13790_LAMBDA_AT * a_floor
    a_m = _ISO13790_A_M_PER_A_FLOOR * a_floor
    H_tr_is = _ISO13790_H_IS * a_t
    H_tr_ms = _ISO13790_H_MS * a_m
    # Windows: ISO 13790 H_tr_w = sum(U_w * A_w), available from TEASER as ua_value_win
    H_tr_w = float(getattr(m1, "ua_value_win", 0.0))
    # Opaque envelope: TEASER's one-element model collapses opaque envelope
    # conductance into ua_value_ow. ISO 13790 places H_tr_em in series with
    # H_tr_ms; invert to extract H_tr_em.
    H_tr_op = float(getattr(m1, "ua_value_ow", 0.0))
    if H_tr_op > 0 and H_tr_ms > 0 and H_tr_op < H_tr_ms:
        H_tr_em = 1.0 / (1.0 / H_tr_op - 1.0 / H_tr_ms)
    else:
        # Degenerate case (very high envelope conductance or missing data):
        # fall back to a direct mapping. The 5R1C result will be approximate
        # but the simulator will still run.
        H_tr_em = H_tr_op
    C_m = _ISO13790_KAPPA_M * a_floor
    return {
        "H_tr_is": float(H_tr_is),
        "H_tr_ms": float(H_tr_ms),
        "H_tr_w": float(H_tr_w),
        "H_tr_em": float(H_tr_em),
        "C_m": float(C_m),
    }


def _compose_7r2c(m4) -> dict:
    """VDI 6007 7R2C parameters from a TEASER four-element model.

    The 7R2C network in EnTiSe (``entise.methods.hvac.R7C2``) uses a
    radiative "star" topology: each internal surface couples to a central
    radiative node ``theta_lu_star`` via a radiative-only resistance, and
    the star node in turn couples to the indoor air node ``theta_air``
    via a convective resistance.

    Mapping:
      R_1_AW, C_1_AW   - outer-wall reduced RC pair (TEASER four-element)
      R_1_IW, C_1_IW   - inner-wall reduced RC pair (TEASER four-element)
      R_alpha_star_AW  - radiative coupling from outer-wall surface to
                          star node: 1 / (alpha_rad_inner_ow * area_ow)
      R_alpha_star_IW  - same for inner-wall surface
      R_alpha_star_IL  - convective leg from star node to indoor air,
                          1 / total_convective_UA over all internal-facing
                          surfaces (OW, IW, ground floor, rooftop, windows)
      R_rest_AW        - remaining outer-wall thermal path beyond the RC pair
    """
    def _r_inv(coeff: float, area: float) -> float:
        if coeff > 0 and area > 0:
            return 1.0 / (coeff * area)
        return float("inf")

    # Total convective UA from all internal surfaces to indoor air. Includes
    # outer walls, inner walls, ground floor, rooftop, and windows. Some
    # element groups may be absent (zero area) depending on the geometry;
    # the guarded form skips those.
    ua_conv_total = 0.0
    for alpha_attr, area_attr in (
        ("alpha_conv_inner_ow", "area_ow"),
        ("alpha_conv_inner_iw", "area_iw"),
        ("alpha_conv_inner_gf", "area_gf"),
        ("alpha_conv_inner_rt", "area_rt"),
        ("alpha_conv_inner_win", "area_win"),
    ):
        a = float(getattr(m4, alpha_attr, 0.0) or 0.0)
        s = float(getattr(m4, area_attr, 0.0) or 0.0)
        if a > 0 and s > 0:
            ua_conv_total += a * s
    R_alpha_star_IL = 1.0 / ua_conv_total if ua_conv_total > 0 else float("inf")

    return {
        "R_1_AW": float(m4.r1_ow),
        "C_1_AW": float(m4.c1_ow),
        "R_1_IW": float(m4.r1_iw),
        "C_1_IW": float(m4.c1_iw),
        "R_alpha_star_AW": _r_inv(float(m4.alpha_rad_inner_ow), float(m4.area_ow)),
        "R_alpha_star_IW": _r_inv(float(m4.alpha_rad_inner_iw), float(m4.area_iw)),
        "R_alpha_star_IL": R_alpha_star_IL,
        "R_rest_AW": float(m4.r_rest_ow),
    }


@dataclass
class TEASERArchetypeProvider:
    """Generate archetypes by running TEASER on a TABULA database.

    Parameters
    ----------
    archetypes_csv : Path
        CSV with one row per archetype. Required columns (canonical
        schema, same names as the parquet output):
        ``archetype_id, construction_year, area_m2, n_floors,
        height_floor_m``.
    construction_data : str
        TEASER construction database key. Default "tabula_de_standard"
        (German envelope archetypes). For other countries, point to the
        matching TABULA package (e.g. "tabula_at_standard" for Austria).
    geometry_data : str
        TEASER geometry preset. Default "tabula_de_single_family_house".
    """

    archetypes_csv: Path
    construction_data: str = "tabula_de_standard"
    geometry_data: str = "tabula_de_single_family_house"

    def get_archetypes(self) -> pd.DataFrame:
        archetypes = _load_archetypes_csv(self.archetypes_csv)
        rows = [self._build_one(row) for row in archetypes.itertuples()]
        df = pd.DataFrame(rows)
        validate_schema(df, ArchetypeSchema.REQUIRED_1R1C, "TEASERArchetypeProvider")
        return df

    def _build_one(self, row: Any) -> dict:
        from teaser.project import Project

        prj = Project()
        prj.add_residential(
            construction_data=self.construction_data,
            geometry_data=self.geometry_data,
            name=f"arch{int(row.archetype_id):02d}",
            year_of_construction=int(row.year_of_construction),
            number_of_floors=int(row.number_of_floors),
            height_of_floors=float(row.height_of_floors),
            net_leased_area=float(row.net_leased_area),
            inner_wall_approximation_approach="teaser_default",
        )
        prj.calc_all_buildings()
        if not prj.buildings:
            raise RuntimeError(
                f"TEASER produced no building for archetype "
                f"{int(row.archetype_id)} (year={int(row.year_of_construction)}). "
                f"Check that {self.construction_data} has data for that year."
            )
        bldg = prj.buildings[0]
        a_floor = float(row.net_leased_area)

        # ── 1-element pass: 1R1C aggregate + 5R1C ISO 13790 ────────────────
        bldg.calc_building_parameter(
            number_of_elements=1, merge_windows=True, used_library="IBPSA"
        )
        zone1 = bldg.thermal_zones[0]
        m1 = zone1.model_attr

        # 1R1C: aggregated envelope resistance and capacitance
        r_1r1c = float(m1.r_total_ow)
        c_1r1c = float(m1.c1_ow) + zone1.volume * zone1.density_air * zone1.heat_capac_air

        # Total transparent envelope area: TEASER applies the construction-
        # database-specific window-to-floor ratio when adding the residential
        # building, so this sum already reflects the TABULA archetype's
        # design intent. Distribution across orientations is applied at
        # simulation time.
        window_area_total = float(sum(w.area for w in zone1.windows))

        five_r_one_c = _compose_5r1c(m1, a_floor)

        # ── 4-element pass: 7R2C VDI 6007 ──────────────────────────────────
        bldg.calc_building_parameter(
            number_of_elements=4, merge_windows=True, used_library="AixLib"
        )
        zone4 = bldg.thermal_zones[0]
        m4 = zone4.model_attr
        seven_r_two_c = _compose_7r2c(m4)

        return {
            "archetype_id": int(row.archetype_id),
            "construction_year": int(row.year_of_construction),
            "area_m2": a_floor,
            "n_floors": int(row.number_of_floors),
            "height_floor_m": float(row.height_of_floors),
            "thermal_resistance": r_1r1c,
            "thermal_capacitance": c_1r1c,
            "window_area_total_m2": window_area_total,
            **five_r_one_c,
            **seven_r_two_c,
        }

    def save(self, path: Path) -> None:
        df = self.get_archetypes()
        path.parent.mkdir(parents=True, exist_ok=True)
        df.to_parquet(path, index=False)


@dataclass
class FileArchetypeProvider:
    """Read a user-supplied tabular archetype file.

    The file may be CSV or parquet; the extension decides. Columns must
    already match ArchetypeSchema.REQUIRED_1R1C (and may include the
    optional 5R1C / 7R2C columns if the user wants to use those models).

    This is the escape hatch for users who already have archetype
    parameters from another source — no TEASER required.
    """

    path: Path

    def get_archetypes(self) -> pd.DataFrame:
        p = Path(self.path)
        if p.suffix.lower() in (".parquet", ".pq"):
            df = pd.read_parquet(p)
        else:
            df = pd.read_csv(p)
        validate_schema(df, ArchetypeSchema.REQUIRED_1R1C, f"FileArchetypeProvider({p})")
        return df

    def save(self, path: Path) -> None:
        df = self.get_archetypes()
        path.parent.mkdir(parents=True, exist_ok=True)
        df.to_parquet(path, index=False)


# Legacy alias — older code and YAML configs reference the CSV-prefixed name.
CSVArchetypeProvider = FileArchetypeProvider
