"""When2Heat cross-validation of the published Germany 2010 dataset.

Paper section: Validation -> Tier 4 (When2Heat aggregate cross-validation).

Compares the temporal shape of our pipeline's national-aggregate
residential heating profile against When2Heat (Ruhnau et al., 2019,
Open Power System Data) — the established European single-RC heat-
demand benchmark. The comparison fills a validation gap that the NREL
EULP-based Tier 1A / Tier 3 tests do not: those validate the
*methodology* under matched ResStock inputs; this validates that the
*actual numbers in the published Germany 2010 parquets* are
consistent with an independent German benchmark.

Scope and limits

  * Heating only. When2Heat does not publish cooling profiles (German
    residential cooling has historically been negligible).
  * Shape-only comparison: both series are normalised before comparing.
    Reasons:
      - our coverage is SFH only; When2Heat covers all residential
        (SFH + MFH + apartments)
      - we do not apply census-equivalent stock-mix weights across
        the 3.3 M building-year combinations
    Absolute MW comparison would require those weights and would
    conflate stock-mix bias with methodology bias. Normalised shape
    isolates the methodology comparison cleanly.
  * The methodologies differ by design: When2Heat = single-RC × HDD ×
    national floor area; ours = 4045 locations × 11 archetypes ×
    74 profiles × hourly RC simulation. A close shape match
    demonstrates that our methodology preserves the temporal heat-
    demand dynamics established in the literature *while* delivering
    per-household variability that single-RC approaches cannot.

Inputs

  * ``output/HC/locXXXX/hc_archYY.parquet`` — pipeline outputs
    (4045 locations × 11 archetypes per location, 74 profiles per file).
    Generated by ``uv run coupled-energy-ts run config/germany_2010.yml``.
  * When2Heat CSV — download from
        https://data.open-power-system-data.org/when2heat/
    Save the CSV (e.g. ``when2heat.csv``) under
    ``validation/germany/data/when2heat.csv``. Pass with
    ``--when2heat-csv`` if elsewhere.

Outputs

  * ``img/de_demand_comparison.png`` and ``.pdf`` — 2-panel figure:
      Panel A: full-year daily-mean overlay (normalised to peak)
      Panel B: peak-week (January) hourly overlay (normalised to peak)
  * ``validation/germany/data/when2heat_metrics.csv`` — Pearson r
    (hourly + daily-mean), normalised RMSE, peak-day correlation.

Usage

    uv run python validation/germany/demand_comparison.py \\
        --when2heat-csv validation/germany/data/when2heat.csv

    # If your HC outputs are elsewhere:
    uv run python validation/germany/demand_comparison.py \\
        --when2heat-csv .../when2heat.csv \\
        --hc-root /path/to/output/HC
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Iterable

import matplotlib as mpl
import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.stats import pearsonr

mpl.rcParams.update({
    "font.size":       12,
    "axes.titlesize":  12,
    "axes.labelsize":  13,
    "xtick.labelsize": 11,
    "ytick.labelsize": 11,
    "legend.fontsize": 11,
    "pdf.fonttype":    42,
    "ps.fonttype":     42,
})

ROOT = Path(__file__).resolve().parents[2]


def aggregate_pipeline_heating(hc_root: Path,
                                cache_path: Path | None = None) -> pd.Series:
    """Stream-aggregate q_heat_w across every (location, archetype, profile)
    combination into a single national-hourly Series.

    Memory-bounded: each file's 74-profile groupby is reduced to one
    row per timestamp before adding to the running total. Works on
    ~45 000 parquets without exceeding a few hundred MB of RAM.
    Progress is reported via a tqdm bar so the user sees ETA at scale.

    If ``cache_path`` is given and exists, load from cache instead. The
    aggregation is deterministic over a fixed pipeline output, so the
    cache is safe to reuse across retries (delete the cache file to
    force a re-aggregation after a fresh pipeline run).
    """
    from tqdm import tqdm

    if cache_path is not None and cache_path.exists():
        print(f"[when2heat] loading cached aggregate from {cache_path}")
        df = pd.read_parquet(cache_path)
        s = df["ours_heating_w"]
        s.index = pd.DatetimeIndex(df.index)
        if s.index.tz is None:
            s.index = s.index.tz_localize("UTC")
        return s.sort_index()

    files = sorted(hc_root.glob("loc*/hc_arch*.parquet"))
    if not files:
        raise FileNotFoundError(
            f"No parquets matching {hc_root}/loc*/hc_arch*.parquet. "
            f"Run 'uv run coupled-energy-ts run config/germany_2010.yml' "
            f"first to populate the dataset.")
    agg: pd.Series | None = None
    for f in tqdm(files, desc="[when2heat] aggregating parquets",
                   unit="file", smoothing=0.05):
        df = pd.read_parquet(f, columns=["timestamp", "q_heat_w"])
        s = df.groupby("timestamp")["q_heat_w"].sum()
        agg = s if agg is None else agg.add(s, fill_value=0.0)
    assert agg is not None
    agg.index = pd.to_datetime(agg.index)
    if agg.index.tz is None:
        agg.index = agg.index.tz_localize("UTC")
    else:
        agg.index = agg.index.tz_convert("UTC")
    agg.name = "ours_heating_w"
    agg = agg.sort_index()

    if cache_path is not None:
        cache_path.parent.mkdir(parents=True, exist_ok=True)
        pd.DataFrame({"ours_heating_w": agg.values},
                     index=agg.index).to_parquet(cache_path)
        print(f"[when2heat] cached aggregate -> {cache_path}")
    return agg


def load_when2heat(csv_path: Path,
                    country: str = "DE",
                    year: int = 2010,
                    column: str | None = None) -> tuple[pd.Series, str]:
    """Pick the most apt single-family-house space-heating column for the
    given country and year from the When2Heat CSV. Returns (series,
    column_name).

    When2Heat publishes both ``*_heat_profile_*`` (normalised, dimensionless,
    annual mean = 1) and ``*_heat_demand_*`` (absolute, MW) columns, split
    by building type (SFH and MFH). The published Germany 2010 dataset uses
    11 SFH archetypes from TABULA-DE, so the apples-to-apples column is
    ``heat_demand_space_SFH``. The ``*_total*`` columns span all sectors
    and end-uses and would force the comparison to absorb DHW, process heat,
    and non-residential demand that our pipeline does not model. Pass
    ``column`` to override the auto-selection explicitly.

    The OPSD When2Heat CSV occasionally has more data fields than header
    columns (multi-line metadata blocks). We read it via the Python engine
    with ``on_bad_lines='skip'`` so a malformed row near the top doesn't
    abort parsing of the 8 760 valid rows we actually need. We also
    restrict to columns we'll use to keep memory and parse time low.
    """
    # OPSD When2Heat CSV is semicolon-delimited, not comma. Detect that
    # by sniffing the header line.
    with open(csv_path, "r", encoding="utf-8") as fh:
        header_line = fh.readline()
    sep = ";" if header_line.count(";") > header_line.count(",") else ","
    print(f"[when2heat] detected delimiter: {sep!r}")

    # First pass: grab just the header to discover columns. The Python
    # engine doesn't accept 'low_memory' so we omit it.
    header_df = pd.read_csv(csv_path, nrows=0, sep=sep,
                              engine="python", on_bad_lines="skip")
    cols_keep = [c for c in header_df.columns
                 if c == "utc_timestamp"
                 or c.startswith(f"{country}_")]
    if not cols_keep:
        raise ValueError(
            f"No '{country}_*' columns and no 'utc_timestamp' in header of "
            f"{csv_path}. First few columns: {list(header_df.columns)[:8]!r}.")
    print(f"[when2heat] reading {len(cols_keep)} columns from CSV "
          f"(of {len(header_df.columns)} total) ...")
    df = pd.read_csv(csv_path, usecols=cols_keep, sep=sep,
                      engine="python", on_bad_lines="skip")
    ts_col = "utc_timestamp" if "utc_timestamp" in df.columns else df.columns[0]
    df[ts_col] = pd.to_datetime(df[ts_col], utc=True, errors="coerce")
    df = df.dropna(subset=[ts_col]).set_index(ts_col)
    df = df.loc[df.index.year == year]

    # Candidate single-family-house space-heating columns, in preference
    # order. When2Heat publishes by building type (SFH / MFH) rather than
    # by an aggregated "residential" tag, so the SFH column is the apples-
    # to-apples match for our SFH-only published dataset. The *_total*
    # variants span all sectors (residential + services) and include DHW
    # and process heat that our pipeline does not model.
    cands = [
        f"{country}_heat_demand_space_SFH",
        f"{country}_heat_profile_space_SFH",
        f"{country}_heat_profile_space",
        f"{country}_heat_demand_total",
    ]
    if column is not None:
        if column not in df.columns:
            raise ValueError(
                f"--column={column!r} not present in {csv_path}. "
                f"Available '{country}_*' columns: "
                f"{sorted(c for c in df.columns if country in c)[:20]!r}")
        chosen: str | None = column
    else:
        chosen = next((c for c in cands if c in df.columns), None)
    if chosen is None:
        # Fall back: any column starting with "<country>_heat" and
        # containing 'space' or 'residential'.
        loose = [c for c in df.columns
                  if c.startswith(f"{country}_heat")
                  and ("space" in c.lower() or "residential" in c.lower())]
        if not loose:
            sample = sorted(c for c in df.columns if country in c)[:10]
            raise ValueError(
                f"No suitable residential-heating column in {csv_path}. "
                f"Tried: {cands!r}. "
                f"Available '{country}_*' columns include: {sample!r}.")
        chosen = loose[0]
    print(f"[when2heat] using column: {chosen}")
    s = pd.to_numeric(df[chosen], errors="coerce").dropna()
    s.name = "when2heat"
    return s, chosen


def normalise_to_peak(s: pd.Series) -> pd.Series:
    p = float(s.max())
    if p <= 0:
        raise ValueError(f"Series '{s.name}' has non-positive peak {p}")
    return s / p


def compute_metrics(ours: pd.Series, theirs: pd.Series) -> dict:
    """Pearson r and normalised RMSE on hourly and daily-mean shapes."""
    common = ours.index.intersection(theirs.index)
    if len(common) == 0:
        raise ValueError("No timestamp overlap between pipeline and When2Heat.")
    o = normalise_to_peak(ours.loc[common])
    t = normalise_to_peak(theirs.loc[common])
    r_h, _ = pearsonr(o.values, t.values)
    rmse_h = float(np.sqrt(((o - t) ** 2).mean()))
    o_d = o.resample("D").mean()
    t_d = t.resample("D").mean()
    r_d, _ = pearsonr(o_d.values, t_d.values)
    rmse_d = float(np.sqrt(((o_d - t_d) ** 2).mean()))
    # Annual-energy ratio (after normalisation)
    e_ratio = float(o.sum() / t.sum())
    return {
        "n_hours": int(len(common)),
        "pearson_r_hourly": float(r_h),
        "pearson_r_daily": float(r_d),
        "rmse_norm_hourly": rmse_h,
        "rmse_norm_daily": rmse_d,
        "energy_ratio_norm": e_ratio,
    }


def pick_peak_week(theirs: pd.Series) -> pd.Timestamp:
    """Pick the week containing the When2Heat hourly peak (winter)."""
    peak_t = theirs.idxmax()
    return (peak_t - pd.Timedelta(days=3)).normalize()


def render_figure(ours: pd.Series, theirs: pd.Series,
                   metrics: dict, out_path: Path,
                   include_hourly: bool = False) -> None:
    """Render the When2Heat comparison figure.

    Default is single-panel (daily-mean only) to match Ruhnau et al.'s
    own validation framing — they validate against daily aggregates
    because hourly shape mixes weather-driven dynamics with country-
    specific behavioural schedules baked into the When2Heat heat-load
    profiles (Hellwig 2003 for DE). Comparing hourly invites a like-
    for-like reading that neither methodology is calibrated for.

    Pass ``include_hourly=True`` to add a peak-week hourly diagnostic
    panel; the hourly Pearson r is in the metrics CSV either way.
    """
    common = ours.index.intersection(theirs.index)
    o = normalise_to_peak(ours.loc[common])
    t = normalise_to_peak(theirs.loc[common])

    if include_hourly:
        fig, axes = plt.subplots(2, 1, figsize=(13, 7))
        ax_a, ax_b = axes
    else:
        fig, ax_a = plt.subplots(1, 1, figsize=(13, 4.5))
        ax_b = None

    # Panel A: full-year daily-mean overlay (the Ruhnau-style validation)
    o_d = o.resample("D").mean()
    t_d = t.resample("D").mean()
    ax_a.plot(t_d.index, t_d.values, color="#555555", lw=1.6,
               label="Reference")
    ax_a.plot(o_d.index, o_d.values, color="#c0392b", lw=1.6, ls="--",
               label="Simulation")
    ax_a.set_xlim(t_d.index.min(), t_d.index.max())
    ax_a.set_ylim(bottom=0)
    ax_a.set_ylabel("Normalized daily-mean heating")
    # In-figure title removed; caption carries the headline metrics
    # (r daily, normalised RMSE, energy ratio).
    ax_a.grid(True, ls=":", alpha=0.4)
    ax_a.xaxis.set_major_locator(mdates.MonthLocator())
    ax_a.xaxis.set_major_formatter(mdates.DateFormatter("%b"))
    ax_a.legend(loc="lower right")

    # Optional Panel B: peak-week hourly overlay
    if ax_b is not None:
        week_start = pick_peak_week(theirs.loc[common])
        week_end = week_start + pd.Timedelta(days=7)
        o_w = o.loc[week_start:week_end]
        t_w = t.loc[week_start:week_end]
        ax_b.plot(t_w.index, t_w.values, color="#555555", lw=1.4,
                   label="Reference")
        ax_b.plot(o_w.index, o_w.values, color="#c0392b", lw=1.4, ls="--",
                   label="Simulation")
        ax_b.set_xlim(week_start, week_end)
        ax_b.set_ylim(bottom=0)
        ax_b.set_ylabel("Normalized hourly heating")
        # In-figure title removed; caption carries the metrics.
        ax_b.grid(True, ls=":", alpha=0.4)
        ax_b.xaxis.set_major_locator(mdates.DayLocator())
        ax_b.xaxis.set_major_formatter(mdates.DateFormatter("%a %d %b"))
        ax_b.legend(loc="upper right")

    fig.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=200)
    fig.savefig(out_path.with_suffix(".pdf"))
    plt.close(fig)
    print(f"\n[when2heat] figure -> {out_path} and {out_path.with_suffix('.pdf')}")


def main() -> None:
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--hc-root", type=Path,
                   default=ROOT / "output" / "HC",
                   help="Pipeline H/C output root (default: ./output/HC)")
    p.add_argument("--when2heat-csv", type=Path,
                   default=ROOT / "validation" / "germany" / "data" / "when2heat.csv",
                   help="Path to the When2Heat CSV (download manually from "
                        "https://data.open-power-system-data.org/when2heat/)")
    p.add_argument("--country", default="DE",
                   help="Country code in When2Heat CSV (default: DE)")
    p.add_argument("--year", type=int, default=2010,
                   help="Year to validate (default: 2010)")
    p.add_argument("--out-fig", type=Path,
                   default=ROOT / "img" / "de_demand_comparison.png")
    p.add_argument("--out-metrics", type=Path,
                   default=ROOT / "validation" / "germany" / "data"
                            / "when2heat_metrics.csv")
    p.add_argument("--cache-path", type=Path,
                   default=ROOT / "validation" / "germany" / "data"
                            / "ours_aggregated.parquet",
                   help="Where to cache the pipeline aggregate (parquet). "
                        "Skips re-aggregation on retries; delete this file "
                        "to force a fresh aggregation after a new pipeline "
                        "run.")
    p.add_argument("--no-cache", action="store_true",
                   help="Disable the aggregation cache (always re-aggregate).")
    p.add_argument("--with-hourly", action="store_true",
                   help="Also render the peak-week hourly diagnostic panel. "
                        "By default the figure is single-panel (daily-mean "
                        "only) to match Ruhnau et al.'s own validation "
                        "framing — they don't compare on hourly shape "
                        "because it conflates weather dynamics with the "
                        "country-specific behavioural schedules embedded "
                        "in their heat-load profiles.")
    p.add_argument("--column", default=None,
                   help="Override the When2Heat column. Default auto-selects "
                        "DE_heat_demand_space_SFH (apples-to-apples for our "
                        "SFH-only published dataset). Use this to force a "
                        "comparison against a *_total* or MFH column.")
    args = p.parse_args()

    if not args.when2heat_csv.exists():
        sys.exit(
            f"When2Heat CSV not found at {args.when2heat_csv}.\n"
            f"Download manually from "
            f"https://data.open-power-system-data.org/when2heat/ "
            f"and save to that path (or pass --when2heat-csv elsewhere)."
        )

    print(f"[when2heat] hc_root = {args.hc_root}")
    print(f"[when2heat] when2heat_csv = {args.when2heat_csv}")
    print(f"[when2heat] country = {args.country}, year = {args.year}\n")

    cache = None if args.no_cache else args.cache_path
    ours = aggregate_pipeline_heating(args.hc_root, cache_path=cache)
    theirs, col = load_when2heat(args.when2heat_csv, country=args.country,
                                  year=args.year, column=args.column)

    print(f"\n[when2heat] our aggregate range: "
          f"{ours.index.min()} -> {ours.index.max()}, n={len(ours):,}")
    print(f"[when2heat] their range: "
          f"{theirs.index.min()} -> {theirs.index.max()}, n={len(theirs):,}")

    metrics = compute_metrics(ours, theirs)
    print("\n=== When2Heat shape-validation metrics ===")
    for k, v in metrics.items():
        print(f"  {k:<22s} = {v}")

    render_figure(ours, theirs, metrics, args.out_fig,
                   include_hourly=args.with_hourly)

    args.out_metrics.parent.mkdir(parents=True, exist_ok=True)
    pd.DataFrame([{
        "country": args.country, "year": args.year,
        "when2heat_column": col, **metrics,
    }]).to_csv(args.out_metrics, index=False)
    print(f"[when2heat] metrics -> {args.out_metrics}")


if __name__ == "__main__":
    main()
